//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceTool {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolWebApp.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accessories.
        /// </summary>
        public static string AccessoriesCol {
            get {
                return ResourceManager.GetString("AccessoriesCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice Bosch.
        /// </summary>
        public static string BoschCodeCol {
            get {
                return ResourceManager.GetString("BoschCodeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione.
        /// </summary>
        public static string DescriptionCol {
            get {
                return ResourceManager.GetString("DescriptionCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FProposal.
        /// </summary>
        public static string FProposalCol {
            get {
                return ResourceManager.GetString("FProposalCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FValue.
        /// </summary>
        public static string FValueCol {
            get {
                return ResourceManager.GetString("FValueCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Id Tool.
        /// </summary>
        public static string IdToolLable {
            get {
                return ResourceManager.GetString("IdToolLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Life.
        /// </summary>
        public static string LifeCol {
            get {
                return ResourceManager.GetString("LifeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Presetting.
        /// </summary>
        public static string PresettingCol {
            get {
                return ResourceManager.GetString("PresettingCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PresettingDiameter.
        /// </summary>
        public static string PresettingDiameterCol {
            get {
                return ResourceManager.GetString("PresettingDiameterCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PresettingQuoteNGEM1.
        /// </summary>
        public static string PresettingQuoteNGEM1Col {
            get {
                return ResourceManager.GetString("PresettingQuoteNGEM1Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PresettingQuoteNGEM2.
        /// </summary>
        public static string PresettingQuoteNGEM2Col {
            get {
                return ResourceManager.GetString("PresettingQuoteNGEM2Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PrimarySharpener.
        /// </summary>
        public static string PrimarySharpenerCol {
            get {
                return ResourceManager.GetString("PrimarySharpenerCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fornitore Primario.
        /// </summary>
        public static string PrimarySupplierCol {
            get {
                return ResourceManager.GetString("PrimarySupplierCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantità.
        /// </summary>
        public static string QuantityCol {
            get {
                return ResourceManager.GetString("QuantityCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refrigeration.
        /// </summary>
        public static string RefrigerationCol {
            get {
                return ResourceManager.GetString("RefrigerationCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SecondarySharpener.
        /// </summary>
        public static string SecondarySharpenerCol {
            get {
                return ResourceManager.GetString("SecondarySharpenerCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fornitore Secondario.
        /// </summary>
        public static string SecondarySupplierCol {
            get {
                return ResourceManager.GetString("SecondarySupplierCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SProposal.
        /// </summary>
        public static string SProposalCol {
            get {
                return ResourceManager.GetString("SProposalCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SValue.
        /// </summary>
        public static string SValueCol {
            get {
                return ResourceManager.GetString("SValueCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Turret.
        /// </summary>
        public static string TurretCodeCol {
            get {
                return ResourceManager.GetString("TurretCodeCol", resourceCulture);
            }
        }
    }
}
